// Name: Shreya De
//Instructor's Name: Lauren Bricker
// TA's Name: Will Bigelow
// Date: 4/18/20182
// This is my custom animation to be used by the overall program.
// It was automatically generated by the StringMaker tool.
// It represents two faces- one regular, and one upside down


let CUSTOM =
" #  #\n" + 
"   \\\n" + 
"-----\n" + 
"=====\n" + 
"-----\n" + 
"  \\\n" + 
"#   #\n";

ANIMATIONS["Custom"] = ANIMATIONS["custom"] = ANIMATIONS["CUSTOM"] = CUSTOM;